// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHTIiOm9DmZo8gt2WCrNb-BAbF7Frn8ic',
    appId: '1:597034612844:web:f2fcbff67be00af23ac049',
    messagingSenderId: '597034612844',
    projectId: 'evently-app-40fb7',
    authDomain: 'evently-app-40fb7.firebaseapp.com',
    storageBucket: 'evently-app-40fb7.firebasestorage.app',
    measurementId: 'G-MCBS4DHEX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsfpOW-g5x-4o2fFZ3OgCyq6L1qlJXjMk',
    appId: '1:597034612844:android:dcd518151f3d9e3a3ac049',
    messagingSenderId: '597034612844',
    projectId: 'evently-app-40fb7',
    storageBucket: 'evently-app-40fb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkJye3kncvgKlfMRGGmxTne8cp8J8nXEY',
    appId: '1:597034612844:ios:ebeb2d8f882f096b3ac049',
    messagingSenderId: '597034612844',
    projectId: 'evently-app-40fb7',
    storageBucket: 'evently-app-40fb7.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkJye3kncvgKlfMRGGmxTne8cp8J8nXEY',
    appId: '1:597034612844:ios:ebeb2d8f882f096b3ac049',
    messagingSenderId: '597034612844',
    projectId: 'evently-app-40fb7',
    storageBucket: 'evently-app-40fb7.firebasestorage.app',
    iosBundleId: 'com.example.eventlyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHTIiOm9DmZo8gt2WCrNb-BAbF7Frn8ic',
    appId: '1:597034612844:web:46f64904459926343ac049',
    messagingSenderId: '597034612844',
    projectId: 'evently-app-40fb7',
    authDomain: 'evently-app-40fb7.firebaseapp.com',
    storageBucket: 'evently-app-40fb7.firebasestorage.app',
    measurementId: 'G-LKQEKXLMCW',
  );
}
